before:
  hooks:
    - 'go mod tidy'

builds:
- env:
    - 'CGO_ENABLED=0'
    - 'GO111MODULE=on'
    - 'GOPROXY=https://proxy.golang.org,direct'
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - '-a'
    - '-trimpath'
  ldflags:
    - '-s'
    - '-w'
    - '-X=main.version={{ .Version }}'
    - '-X=main.commit={{ .Commit }}'
    - '-extldflags=-static'
  goos:
    - 'darwin'
    - 'linux'
    - 'windows'
  goarch:
    - 'amd64'
    - 'arm64'
  binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
- format: 'zip'
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: 'sha256'

signs:
  - artifacts: 'checksum'
    args:
      # if you are using this is a GitHub action or some other automated pipeline, you
      # need to pass the batch flag to indicate its not interactive.
      - '--batch'
      - '--local-user'
      - '{{ .Env.GPG_FINGERPRINT }}' # set this environment variable for your signing key
      - '--output'
      - '${signature}'
      - '--detach-sign'
      - '${artifact}'

release:
  draft: false
